-- CREATE THE DATABASE
CREATE DATABASE EZSHOP;
-- USE DATABASE
USE EZSHOP;
-- CREATE TABLE PRODUCTS
DROP TABLE PRODUCT;
CREATE TABLE PRODUCTS (PRODUCT_ID CHAR(5), PRODUCT_NAME VARCHAR(25), PRICE INT, QUANTITY INT);
INSERT INTO PRODUCTS VALUES ('P01', 'SWW',200,5);
INSERT INTO PRODUCTS VALUES ('P02', 'DW',250,10);
SELECT * FROM PRODUCTS;