-- CREATE THE DATABASE
CREATE DATABASE FMCGGLOBALDB;
-- USE DATABASE
USE FMCGGLOBALDB;
-- CREATE TABLES WITH CONSTRAINTS
CREATE TABLE PRODUCTS(PRODUCT_ID .....);
CREATE TABLE SUPPLIERS......
-- INSERT RECORDS
INSERT INTO PRODUCTS VALUES (1, "BOURNVILLE",....); (5 ROWS)
INSERT INTO SUPPLIERS (5 ROWS)