-- CREATE THE DATABASE
CREATE DATABASE FMCGGLOBALDB;
-- USE DATABASE
USE FMCGGLOBALDB;
-- CREATE TABLES WITH CONSTRAINTS
CREATE TABLE PRODUCT(PRODUCT_ID .....);
CREATE TABLE ......
-- INSERT RECORDS
INSERT INTO PRODUCT VALUES (1, "BOURNVILLE",....);